### ISSUE TITLE
Deployment on Netlify

### ISSUE THREAD

**Issue by Siddhant-K-code** [imabp/PR_Visualizer#25]
Are there any plans to deploy this project, it will be good and easy to use it :)

**Comment by imabp** [comment]
Hi @Siddhant-K-code 
Apologies for the late reply. As this is the fellowship sprint 1 project.
So we are active now on the project now. You are also welcomed to contribute as it is completely an Open Source Project.

We are surely going to look at the deployment after #26
Feel free to contribute by creating a sub-issue, under #26
