### ISSUE TITLE
Duplicate Group need to be Removed

### ISSUE THREAD

**Issue by ksdkamesh99** [imabp/PR_Visualizer#28]
While I was exploring the app i found a bug in the PR Visualiser. That is when we create a group if we recreate a group with the same name it is been created. So I want to modify a function while creating a group to check whether the group exists or not.

Here is the screenshot of the above situation.

![image](https://user-images.githubusercontent.com/46109386/114887507-24e70d80-9e26-11eb-976d-c5620b8b77af.png)

**Comment by ksdkamesh99** [comment]
@wilkesalex @Nuage21 @imabp I want to work on this issue kindly assign it to me

**Comment by imabp** [comment]
Hi @ksdkamesh99 did you go through issue #26

**Comment by ksdkamesh99** [comment]
Yes @imabp
